version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - db
volumes:
  pgdata:



